### ISSUE TITLE
Error when launching project

### ISSUE THREAD

**Issue by galli-leo** [lion03/KinectDemoRoom#2]
When I try to launch the Project it gives me this error:
`InternalUtils.SafeCopyFile: WARNING: SafeCopyFile Exception was Exception in mscorlib: Access to the path 'L:\Unreal Projects\KinectDemoRoom-develop\Plugins\KinectV2\Source\ThirdParty\Redist\Face\x64\NuiDataBase' is denied.
LogPlayLevel: Stacktrace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
LogPlayLevel:    at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
LogPlayLevel:    at AutomationTool.InternalUtils.SafeCopyFile(String SourceName, String TargetName, Boolean bQuiet, Boolean bFilterSpecialLinesFromIniFiles)`

I think it has something to do with a permission issue.

**Comment by TheAgent007** [comment]
Did you ever solve this? Same issues.

**Comment by fweidner** [comment]
Same.
